const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
const el={text:$("#patentText"),file:$("#fileInput"),choose:$("#chooseFileButton"),drop:$("#dropZone"),analyze:$("#analyzeButton"),sample:$("#sampleButton"),pdf:$("#downloadPdfButton"),clear:$("#clearButton"),status:$("#documentStatus"),kw:$("#keywordList"),cl:$("#clusterList"),kwc:$("#keywordCount"),clc:$("#clusterCount"),wc:$("#wordCount"),signals:$("#signalGrid"),insight:$("#insightBox"),en:$("#englishModeButton"),ja:$("#japaneseModeButton"),eyebrow:$(".eyebrow"),title:$("h1"),uploadTitle:$("#uploadTitle"),uploadHelp:$("#uploadHelp"),textLabel:$("#textLabel"),kt:$("#keywordsTab"),ct:$("#clustersTab"),st:$("#summaryTab"),kh:$("#keywordsHeading"),ch:$("#clustersHeading"),sh:$("#signalsHeading")};
let lang="en",statusKey="empty",statusText="",last=null;
const I={en:{pageTitle:"Patent Keyword Extractor",eyebrow:"Patent analysis",title:"Keyword Extractor",uploadTitle:"Upload patent text",uploadHelp:"Drop a text file here or choose one from your device.",choose:"Choose file",textLabel:"Patent text",ph:"Paste the abstract, claims, or full patent description here...",analyze:"Extract keywords",sample:"Load sample",pdf:"Download PDF",clear:"Clear text",tabs:["Keywords","Clusters","Signals"],heads:["Technical Keywords","CPC/IPC-like Clusters","Document Signals"],empty:"No document loaded",draft:"Draft text",ready:"Analysis ready",sampleStatus:"Sample loaded",kwc:n=>`${n} found`,clc:n=>`${n} matches`,wc:n=>`${n} words`,emptyKw:"Add patent text to extract ranked technical terms.",emptyCl:"Clusters appear after analysis.",emptyIn:"Analysis notes will appear here.",noKw:"No strong technical keywords were found. Try adding more patent text.",noCl:"No CPC/IPC-like clusters matched yet.",occ:n=>`${n} occurrence${n===1?"":"s"}`,term:"term",phrase:"phrase",fit:n=>`${n}% fit`,conf:{high:"high confidence",medium:"medium confidence",low:"low confidence"},sig:["Sections","Unique terms","Claims cues","Technical density"],none:"none",noCluster:"no clear cluster",alert:"Add patent text before downloading a PDF.",report:"Patent Keyword Report",sub:"Generated from the current extractor results",ins:(k,c)=>`Strongest signal: ${k}. Closest classification-style area: ${c}. Use these clusters as research prompts, not as legal classification advice.`},ja:{pageTitle:"特許キーワード抽出ツール",eyebrow:"特許分析",title:"キーワード抽出",uploadTitle:"特許テキストをアップロード",uploadHelp:"テキストファイルをここにドロップ、または端末から選択してください。",choose:"ファイル選択",textLabel:"特許テキスト",ph:"要約、請求項、明細書本文をここに貼り付けてください...",analyze:"キーワード抽出",sample:"サンプル読込",pdf:"PDF出力",clear:"テキストを消去",tabs:["キーワード","分類候補","シグナル"],heads:["技術キーワード","CPC/IPC風クラスター","文書シグナル"],empty:"文書未読込",draft:"入力中",ready:"分析完了",sampleStatus:"サンプル読込済み",kwc:n=>`${n}件`,clc:n=>`${n}件`,wc:n=>`${n}語相当`,emptyKw:"特許テキストを追加すると、技術用語を順位付けして抽出します。",emptyCl:"分析後に分類候補が表示されます。",emptyIn:"分析メモがここに表示されます。",noKw:"強い技術キーワードが見つかりませんでした。特許テキストを増やしてください。",noCl:"一致するCPC/IPC風クラスターはまだありません。",occ:n=>`${n}回出現`,term:"単語",phrase:"複合語",fit:n=>`適合度 ${n}%`,conf:{high:"信頼度 高",medium:"信頼度 中",low:"信頼度 低"},sig:["セクション","固有語","請求項表現","技術密度"],none:"なし",noCluster:"明確な分類なし",alert:"PDFを出力する前に特許テキストを入力してください。",report:"特許キーワードレポート",sub:"現在の抽出結果から生成",ins:(k,c)=>`最も強いシグナル: ${k}。近い分類領域: ${c}。この分類候補は調査の入口であり、法的な分類判断ではありません。`}};
const stop=new Set("about above after again against also although among and another any are because been being between both but can claim claimed claims comprises comprising consists containing could described device does each embodiment embodiments fig figure first for from has have having herein includes including into its may more not one onto other present provided said second such than that the their then thereof these this through using when wherein which while with within would".split(" "));
const generic=new Set("apparatus claim claims configured device embodiment embodiments example examples invention method methods module plurality present provided system systems".split(" "));
const jpStop="する される した して および または ある いる こと もの ため これ それ 当該 本発明 実施形態 第 前記 上記 以下 以上 複数 少なくとも".split(" ");
const jpGeneric="本発明 実施形態 請求項 装置 方法 システム 構成 複数 一例 発明".split(" ");
const jpHints="制御装置 制御部 処理装置 プロセッサ メモリ 記憶部 学習モデル 機械学習 ニューラルネットワーク 推論 分類 特徴量 データセット 通信 無線 ネットワーク パケット 信号 送信 受信 アンテナ センサ 測定 検出 閾値 電圧 電流 温度 電池 バッテリ 車両 自律走行 経路 半導体 基板 電極 回路 トランジスタ 膜 化合物 ポリマー タンパク質 細胞 抗体 医療 患者 診断 治療 流体 圧力 熱交換器 冷却 フィルタ 膜分離".split(" ");
const clusters=[
["G06F / G06N","Computing, data processing, machine learning","計算機、データ処理、機械学習","processor memory model neural training inference algorithm dataset classification feature vector software computer".split(" "),"プロセッサ メモリ モデル ニューラル 学習 推論 アルゴリズム データセット 分類 特徴量 ベクトル ソフトウェア 計算機 記憶部".split(" ")],
["H04L / H04W","Digital communication and wireless networks","デジタル通信、無線ネットワーク","network wireless packet signal transmission communication channel uplink downlink antenna protocol latency".split(" "),"ネットワーク 無線 パケット 信号 送信 受信 通信 チャネル アップリンク ダウンリンク アンテナ プロトコル 遅延".split(" ")],
["A61B / A61M","Medical diagnostics, therapy, and instruments","医療診断、治療、医療機器","patient medical sensor tissue implant catheter diagnostic therapy biomarker physiological dose surgical".split(" "),"患者 医療 センサ 組織 インプラント カテーテル 診断 治療 バイオマーカー 生体 投与量 外科".split(" ")],
["B60W / G08G","Vehicle control, navigation, and transport systems","車両制御、ナビゲーション、交通システム","vehicle autonomous route brake steering traffic navigation driver lidar radar collision fleet".split(" "),"車両 自律 経路 ブレーキ 操舵 交通 ナビゲーション 運転者 ライダー レーダ 衝突 車隊".split(" ")],
["H01L / H05K","Semiconductors, circuits, and electronics assemblies","半導体、回路、電子実装","semiconductor substrate transistor electrode circuit dielectric wafer package interconnect layer gate chip".split(" "),"半導体 基板 トランジスタ 電極 回路 誘電体 ウェハ パッケージ 配線 層 ゲート チップ".split(" ")],
["C07D / C12N","Chemistry, compounds, biotechnology","化学、化合物、バイオテクノロジー","compound polymer enzyme nucleic protein cell culture catalyst molecule composition pharmaceutical antibody".split(" "),"化合物 ポリマー 酵素 核酸 タンパク質 細胞 培養 触媒 分子 組成物 医薬 抗体".split(" ")],
["B01D / F25B","Separation, filtration, thermal and process apparatus","分離、濾過、熱処理装置","filter membrane fluid pressure heat cooling exchanger separator flow gas liquid temperature".split(" "),"フィルタ 膜 流体 圧力 熱 冷却 熱交換器 分離器 流量 気体 液体 温度".split(" ")],
["G01N / G01R","Measurement, testing, and sensing","測定、試験、センシング","measurement detect sensor calibration sample spectral voltage current probe analyte monitoring threshold".split(" "),"測定 検出 センサ 校正 試料 スペクトル 電圧 電流 プローブ 分析対象 監視 閾値".split(" ")]
].map(([code,title,jaTitle,terms,jaTerms])=>({code,title,jaTitle,terms,jaTerms}));
const samples={en:`A system for predictive thermal management of battery modules in an electric vehicle includes temperature sensors coupled to battery cells, memory storing a trained machine learning model, and a processor configured to receive sensor measurements. The processor extracts voltage, current, state-of-charge, and ambient temperature features and predicts a thermal runaway risk score. When the risk score exceeds a threshold, the system adjusts coolant flow through a heat exchanger, modifies charging current, and transmits a warning packet to a vehicle control network.`,ja:`電動車両の電池モジュールを予測的に熱管理する制御装置は、電池セルに結合された複数の温度センサと、学習済みの機械学習モデルを記憶するメモリと、センサ測定値を受信するプロセッサとを備える。プロセッサは、電圧、電流、充電状態、および外気温度の特徴量を抽出し、各セル群について熱暴走リスクスコアを推定する。リスクスコアが閾値を超えた場合、熱交換器を通る冷却流量を調整し、車両制御ネットワークへ警告パケットを送信する。`};
const tr=()=>I[lang],hasJa=s=>/[\u3040-\u30ff\u3400-\u9fff]/.test(s),esc=s=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),fmt=s=>hasJa(s)?s:s.replace(/\b[a-z]/g,m=>m.toUpperCase());
function enTokens(t){return t.toLowerCase().replace(/[^a-z0-9\-\s]/g," ").split(/\s+/).filter(Boolean).map(x=>x.replace(/^-+|-+$/g,"").replace(/(ing|tion|ions|ment|ments|ed|es|s)$/i,""));}
function cleanJa(s){return String(s).replace(/[。、，．・「」『』（）()[\]【】]/g,"").replace(/^(前記|上記|当該|該|その|この|各|複数の|少なくとも一つの|一つの)+/g,"").replace(/(する|される|した|している|して|の)$/g,"");}
function goodJa(s){return s&&s.length>=2&&s.length<=18&&!jpGeneric.includes(s)&&!jpStop.some(w=>s===w||s.endsWith(w));}
function jaTokens(t){const compact=t.replace(/\s+/g,"");const out=jpHints.filter(w=>compact.includes(w));const re=/[\u3400-\u9fff\u30a0-\u30ffー]{0,8}(制御装置|制御部|処理装置|記憶部|学習モデル|機械学習|ニューラルネットワーク|特徴量|データセット|ネットワーク|パケット|アンテナ|センサ|測定|検出|閾値|電圧|電流|温度|電池|バッテリ|車両|経路|半導体|基板|電極|回路|トランジスタ|化合物|ポリマー|タンパク質|細胞|抗体|診断|治療|流体|圧力|熱交換器|冷却|フィルタ|膜分離)/g;for(const m of t.matchAll(re))out.push(m[0]);out.push(...(t.match(/[\u30a0-\u30ffー]{3,18}/g)||[]));return out.map(cleanJa).filter(goodJa);}
function technical(x){if(!x||x.length<2)return false;if(hasJa(x))return goodJa(x);return x.length>=4&&!stop.has(x)&&!/^[0-9]+$/.test(x)&&/[a-z]/.test(x)&&!generic.has(x);}
function evidence(text,term){const i=text.toLowerCase().indexOf(term.toLowerCase());if(i<0)return"";const a=Math.max(0,i-42),b=Math.min(text.length,i+term.length+42);return`${a?"...":""}${text.slice(a,b).replace(/\s+/g," ").trim()}${b<text.length?"...":""}`;}
function boost(term,text){let b=0;for(const c of clusters)for(const w of [...c.terms,...c.jaTerms])if(term.includes(w))b+=2.2;if(/(control|sensor|model|processor|composition|interface)/.test(term))b+=1.3;if(/(制御|センサ|モデル|組成物|インターフェース)/.test(term))b+=1.3;const i=text.toLowerCase().indexOf(term.toLowerCase());if(i>=0&&/abstract|summary|claim|claims|要約|請求項|発明の概要/.test(text.toLowerCase().slice(Math.max(0,i-220),i+220)))b+=1.5;return b;}
function extract(text){const counts=new Map,phrases=new Map,et=enTokens(text),jt=jaTokens(text);for(const tok of [...et,...jt])if(technical(tok))counts.set(tok,(counts.get(tok)||0)+1);for(let n=2;n<=3;n++)for(let i=0;i<=et.length-n;i++){const p=et.slice(i,i+n).filter(technical);if(p.length===n&&!p.every(x=>generic.has(x)))phrases.set(p.join(" "),(phrases.get(p.join(" "))||0)+1)}for(const w of jpHints){const c=text.split(w).length-1;if(c&&goodJa(w))counts.set(w,Math.max(counts.get(w)||0,c))}const score=(term,c)=>Math.min(c,6)*1.2+(hasJa(term)?Math.min(term.length,10)/2.8:Math.log(2+term.length))+boost(term,text);const a=[...[...counts].map(([term,count])=>({term,count,type:"term",score:score(term,count),evidence:evidence(text,term)})),...[...phrases].filter(([p,c])=>c>1||clusters.some(r=>r.terms.some(w=>p.includes(w)))).map(([term,count])=>({term,count,type:"phrase",score:score(term,count)+term.split(" ").length*1.2,evidence:evidence(text,term)}))];const seen=new Set;return a.filter(x=>x.score>2.4).sort((a,b)=>b.score-a.score||b.count-a.count||a.term.localeCompare(b.term,lang==="ja"?"ja":"en")).filter(x=>{const k=x.term;if(seen.has(k))return false;seen.add(k);return true}).slice(0,18)}
function scoreClusters(text,kws){const terms=new Set([...enTokens(text),...jaTokens(text)].filter(technical));const src=(text+" "+kws.map(k=>k.term).join(" ")).toLowerCase();return clusters.map(c=>{const me=c.terms.filter(w=>new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"i").test(src)||terms.has(w));const mj=c.jaTerms.filter(w=>terms.has(w)||src.includes(w.toLowerCase()));const matched=[...new Set([...me,...mj])];const support=kws.filter(k=>matched.some(w=>k.term.includes(w)||w.includes(k.term))).length;const score=Math.min(98,Math.round(matched.length*9+support*4+(matched.length>=3?12:0)));return{...c,matched,score,confidence:score>=70?"high":score>=42?"medium":"low"}}).filter(c=>c.matched.length>=2||c.score>=38).sort((a,b)=>b.score-a.score||b.matched.length-a.matched.length).slice(0,5)}
function signals(text,kws){const toks=[...enTokens(text),...jaTokens(text)].filter(technical),u=new Set(toks);const sec=[...(text.match(/\b(abstract|background|summary|description|claims?|examples?)\b/gi)||[]),...(text.match(/(要約|背景技術|発明の概要|詳細な説明|請求項|実施例)/g)||[])];const cue=[...(text.match(/\b(wherein|comprising|configured to|adapted to|consisting of|according to claim)\b/gi)||[]),...(text.match(/(備える|含む|構成され|請求項|であって|特徴とする|有する)/g)||[])];return{words:enTokens(text).length+(hasJa(text)?jaTokens(text).length:0),uniqueTerms:u.size,sections:new Set(sec.map(x=>x.toLowerCase())).size,claimsCues:cue.length,density:toks.length?Math.min(100,Math.round(u.size/toks.length*100)):0,topKeyword:kws[0]?.term||tr().none}}
const AI_ENDPOINT="https://xokeajplozstmjpuigia.supabase.co/functions/v1/openai-proxy";
function localAnalysis(text){const keywords=extract(text),clusters=scoreClusters(text,keywords),sig=signals(text,keywords);return{text,language:lang,keywords,clusters,signals:sig,source:"local"}}
function parseJsonish(value){if(!value)return null;if(typeof value==="object")return value;if(typeof value!=="string")return null;const cleaned=value.trim().replace(/^```(?:json)?\s*/i,"").replace(/```$/,"" ).trim();try{return JSON.parse(cleaned)}catch{}const a=cleaned.indexOf("{"),b=cleaned.lastIndexOf("}");if(a>=0&&b>a){try{return JSON.parse(cleaned.slice(a,b+1))}catch{}}return null}
function normalizeKeyword(x,i){if(!x)return null;const term=String(x.term||x.keyword||x.text||x.name||"").trim();if(!term)return null;const count=Math.max(1,Number(x.count||x.occurrences||1)||1);const score=Number(x.score||x.relevance||x.weight||(18-i));return{term,count,type:x.type==="phrase"||term.includes(" ")?"phrase":"term",score:Number.isFinite(score)?score:18-i,evidence:String(x.evidence||x.snippet||x.reason||"").slice(0,180)}}
function normalizeCluster(x,i){if(!x)return null;const code=String(x.code||x.classification||x.cpc||x.ipc||"").trim();const title=String(x.title||x.name||x.area||"").trim();if(!code&&!title)return null;const matched=Array.isArray(x.matched)?x.matched:Array.isArray(x.terms)?x.terms:Array.isArray(x.keywords)?x.keywords:[];const score=Math.max(1,Math.min(98,Math.round(Number(x.score||x.fit||x.confidenceScore||(80-i*8))||80-i*8)));let confidence=String(x.confidence||"").toLowerCase();if(!["high","medium","low"].includes(confidence))confidence=score>=70?"high":score>=42?"medium":"low";return{code:code||`AI-${i+1}`,title:title||code,jaTitle:String(x.jaTitle||x.japaneseTitle||title||code),matched:[...new Set(matched.map(v=>String(v).trim()).filter(Boolean))].slice(0,8),score,confidence}}
function normalizeSignals(x,fallbackKeywords){const base=signals(el.text.value.trim(),fallbackKeywords);if(!x||typeof x!=="object")return base;return{words:Number(x.words)||base.words,uniqueTerms:Number(x.uniqueTerms||x.unique_terms)||base.uniqueTerms,sections:Number(x.sections)||base.sections,claimsCues:Number(x.claimsCues||x.claims_cues)||base.claimsCues,density:Number(x.density)||base.density,topKeyword:String(x.topKeyword||x.top_keyword||fallbackKeywords[0]?.term||base.topKeyword)}}
function normalizeAiAnalysis(raw,text,fallback){const data=parseJsonish(raw?.analysis)||parseJsonish(raw?.result)||parseJsonish(raw?.output)||parseJsonish(raw?.content)||parseJsonish(raw?.message)||parseJsonish(raw)||{};const kws=(Array.isArray(data.keywords)?data.keywords:Array.isArray(data.technicalKeywords)?data.technicalKeywords:[]).map(normalizeKeyword).filter(Boolean).slice(0,18);const cls=(Array.isArray(data.clusters)?data.clusters:Array.isArray(data.classifications)?data.classifications:Array.isArray(data.cpcIpcClusters)?data.cpcIpcClusters:[]).map(normalizeCluster).filter(Boolean).slice(0,5);if(!kws.length&&!cls.length)return fallback;const keywords=kws.length?kws:fallback.keywords;const clusters=cls.length?cls:scoreClusters(text,keywords);return{text,language:lang,keywords,clusters,signals:normalizeSignals(data.signals||data.documentSignals,keywords),source:"ai"}}
async function analyze(){const text=el.text.value.trim();if(!text){renderEmpty();return}setStatus("draft");el.analyze.disabled=true;const fallback=localAnalysis(text);try{const response=await fetch(AI_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,prompt:text,language:lang})});if(!response.ok)throw new Error(`AI proxy returned ${response.status}`);const data=await response.json();last=normalizeAiAnalysis(data,text,fallback)}catch(err){console.warn("AI parsing failed; using local fallback",err);last=fallback}finally{renderKeywords(last.keywords);renderClusters(last.clusters);renderSignals(last.signals,last.clusters);setStatus("ready");el.analyze.disabled=false}}
function renderKeywords(kws){el.kwc.textContent=tr().kwc(kws.length);if(!kws.length){el.kw.className="keyword-list empty-state";el.kw.textContent=tr().noKw;return}const max=Math.max(...kws.map(x=>x.score));el.kw.className="keyword-list";el.kw.innerHTML=kws.map((x,i)=>`<article class="keyword-item"><span class="rank">${i+1}</span><div><div class="keyword-name">${esc(fmt(x.term))}</div><div class="keyword-meta">${x.type==="phrase"?tr().phrase:tr().term} · ${tr().occ(x.count)}</div>${x.evidence?`<div class="keyword-evidence">${esc(x.evidence)}</div>`:""}</div><div class="score-bar"><span style="width:${Math.max(12,Math.round(x.score/max*100))}%"></span></div></article>`).join("")}
function renderClusters(cls){el.clc.textContent=tr().clc(cls.length);if(!cls.length){el.cl.className="cluster-list empty-state";el.cl.textContent=tr().noCl;return}el.cl.className="cluster-list";el.cl.innerHTML=cls.map(c=>`<article class="cluster-item"><div class="cluster-top"><span class="cluster-code">${esc(c.code)}</span><span class="cluster-score">${tr().fit(c.score)} · ${tr().conf[c.confidence]}</span></div><div class="cluster-title">${esc(lang==="ja"?c.jaTitle:c.title)}</div><div class="chip-row">${c.matched.map(w=>`<span class="chip">${esc(w)}</span>`).join("")}</div></article>`).join("")}
function renderSignals(s,cls){el.wc.textContent=tr().wc(s.words);el.signals.innerHTML=`<div><dt>${tr().sig[0]}</dt><dd>${s.sections}</dd></div><div><dt>${tr().sig[1]}</dt><dd>${s.uniqueTerms}</dd></div><div><dt>${tr().sig[2]}</dt><dd>${s.claimsCues}</dd></div><div><dt>${tr().sig[3]}</dt><dd>${s.density}%</dd></div>`;const c=cls[0]?(lang==="ja"?cls[0].jaTitle:cls[0].title):tr().noCluster;el.insight.textContent=tr().ins(fmt(s.topKeyword),c)}
function renderEmpty(){last=null;setStatus("empty");el.kwc.textContent=tr().kwc(0);el.clc.textContent=tr().clc(0);el.wc.textContent=tr().wc(0);el.kw.className="keyword-list empty-state";el.kw.textContent=tr().emptyKw;el.cl.className="cluster-list empty-state";el.cl.textContent=tr().emptyCl;el.signals.innerHTML=`<div><dt>${tr().sig[0]}</dt><dd>0</dd></div><div><dt>${tr().sig[1]}</dt><dd>0</dd></div><div><dt>${tr().sig[2]}</dt><dd>0</dd></div><div><dt>${tr().sig[3]}</dt><dd>0%</dd></div>`;el.insight.textContent=tr().emptyIn}
function setStatus(k,v=""){statusKey=k;statusText=v;el.status.textContent={empty:tr().empty,draft:tr().draft,ready:tr().ready,sample:tr().sampleStatus,file:statusText}[statusKey]||tr().empty}
function setLang(l){lang=l;document.documentElement.lang=l;document.title=tr().pageTitle;el.en.classList.toggle("active",l==="en");el.ja.classList.toggle("active",l==="ja");el.eyebrow.textContent=tr().eyebrow;el.title.textContent=tr().title;el.uploadTitle.textContent=tr().uploadTitle;el.uploadHelp.textContent=tr().uploadHelp;el.choose.textContent=tr().choose;el.textLabel.textContent=tr().textLabel;el.text.placeholder=tr().ph;el.analyze.textContent=tr().analyze;el.sample.textContent=tr().sample;el.pdf.textContent=tr().pdf;el.clear.title=tr().clear;el.clear.setAttribute("aria-label",tr().clear);[el.kt.textContent,el.ct.textContent,el.st.textContent]=tr().tabs;[el.kh.textContent,el.ch.textContent,el.sh.textContent]=tr().heads;el.text.value.trim()?analyze():renderEmpty()}
function reportLines(a){const L=I[a.language],lab=c=>a.language==="ja"?c.jaTitle:c.title,lines=[{text:L.report,size:34,w:800,c:"#18201d",g:8},{text:L.sub,size:15,c:"#66736f",g:18},{text:`${L.wc(a.signals.words)} · ${L.kwc(a.keywords.length)} · ${L.clc(a.clusters.length)}`,size:14,c:"#176b61",g:24},{text:L.heads[0],size:20,w:800,c:"#18201d",g:10}];(a.keywords.length?a.keywords:[]).forEach((k,i)=>lines.push({text:`${i+1}. ${fmt(k.term)}  ${L.occ(k.count)}`,size:13,c:"#24312d",g:6}));if(!a.keywords.length)lines.push({text:L.noKw,size:13,c:"#66736f",g:8});lines.push({text:L.heads[1],size:20,w:800,c:"#18201d",g:12,b:18});a.clusters.forEach(c=>{lines.push({text:`${c.code}  ${lab(c)}  ${L.fit(c.score)} · ${L.conf[c.confidence]}`,size:14,w:800,c:"#3b668f",g:6});lines.push({text:c.matched.join(", "),size:12,c:"#66736f",g:10})});if(!a.clusters.length)lines.push({text:L.noCl,size:13,c:"#66736f",g:8});lines.push({text:L.heads[2],size:20,w:800,c:"#18201d",g:12,b:18});for(const [i,v] of [a.signals.sections,a.signals.uniqueTerms,a.signals.claimsCues,`${a.signals.density}%`].entries())lines.push({text:`${L.sig[i]}: ${v}`,size:13,c:"#24312d",g:i===3?14:5});lines.push({text:L.ins(fmt(a.signals.topKeyword),a.clusters[0]?lab(a.clusters[0]):L.noCluster),size:13,c:"#176b61",g:18});return lines}
function wrap(ctx,s,max){const toks=hasJa(s)?[...s]:String(s).split(/\s+/);let line="",out=[];for(const t of toks){const sep=hasJa(s)?"":" ",test=line?line+sep+t:t;if(ctx.measureText(test).width>max&&line){out.push(line);line=t}else line=test}if(line)out.push(line);return out}
function pages(lines){const W=1240,H=1754,M=92,make=()=>{const c=document.createElement("canvas"),x=c.getContext("2d");c.width=W;c.height=H;x.fillStyle="#fbfcfa";x.fillRect(0,0,W,H);x.fillStyle="#176b61";x.fillRect(0,0,14,H);x.textBaseline="top";return c};let c=make(),x=c.getContext("2d"),y=M,out=[];for(const l of lines){y+=l.b||0;x.font=`${l.w||500} ${l.size*2}px Inter, "Yu Gothic", Meiryo, Arial, sans-serif`;const ws=wrap(x,l.text,W-M*2),bh=ws.length*l.size*2*1.38+l.g*2;if(y+bh>H-M){out.push(c);c=make();x=c.getContext("2d");y=M;x.font=`${l.w||500} ${l.size*2}px Inter, "Yu Gothic", Meiryo, Arial, sans-serif`}x.fillStyle=l.c;for(const w of ws){x.fillText(w,M,y);y+=l.size*2*1.38}y+=l.g*2}out.push(c);return out.map(p=>({w:p.width,h:p.height,b:dataBytes(p.toDataURL("image/jpeg",.92))}))}
function dataBytes(url){const bin=atob(url.split(",")[1]),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u}
function imagePdf(imgs){const enc=new TextEncoder,ch=[],off=[];let pos=0,pw=595.28,ph=841.89;const wr=s=>{const b=typeof s==="string"?enc.encode(s):s;ch.push(b);pos+=b.length},obj=(id,parts)=>{off[id]=pos;wr(`${id} 0 obj\n`);parts.forEach(wr);wr("\nendobj\n")};wr("%PDF-1.4\n%ÿÿÿÿ\n");obj(1,["<< /Type /Catalog /Pages 2 0 R >>"]);obj(2,[`<< /Type /Pages /Count ${imgs.length} /Kids [${imgs.map((_,i)=>`${3+i*3} 0 R`).join(" ")}] >>`]);imgs.forEach((im,i)=>{const p=3+i*3,img=p+1,ct=p+2,n=`Im${i+1}`,stream=`q\n${pw} 0 0 ${ph} 0 0 cm\n/${n} Do\nQ`;obj(p,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /${n} ${img} 0 R >> >> /Contents ${ct} 0 R >>`]);obj(img,[`<< /Type /XObject /Subtype /Image /Width ${im.w} /Height ${im.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${im.b.length} >>\nstream\n`,im.b,"\nendstream"]);obj(ct,[`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`])});const xref=pos,cnt=2+imgs.length*3;wr(`xref\n0 ${cnt+1}\n0000000000 65535 f \n`);for(let i=1;i<=cnt;i++)wr(`${String(off[i]).padStart(10,"0")} 00000 n \n`);wr(`trailer\n<< /Size ${cnt+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const out=new Uint8Array(pos);let cur=0;for(const c of ch){out.set(c,cur);cur+=c.length}return out}
function downloadPdf(){if(!el.text.value.trim())return alert(tr().alert);if(!last||last.text!==el.text.value.trim()||last.language!==lang)analyze();const blob=new Blob([imagePdf(pages(reportLines(last)))],{type:"application/pdf"}),a=document.createElement("a"),d=new Date().toISOString().slice(0,10),u=URL.createObjectURL(blob);a.href=u;a.download=lang==="ja"?`特許キーワードレポート-${d}.pdf`:`patent-keyword-report-${d}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.tab}Panel`).classList.add('active')}));$$('.language-button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.language)));el.choose.onclick=()=>el.file.click();el.file.onchange=()=>{const f=el.file.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{el.text.value=String(r.result||"");setStatus("file",f.name);analyze()};r.readAsText(f)};el.drop.ondragover=e=>{e.preventDefault();el.drop.classList.add('dragging')};el.drop.ondragleave=()=>el.drop.classList.remove('dragging');el.drop.ondrop=e=>{e.preventDefault();el.drop.classList.remove('dragging');const f=e.dataTransfer.files?.[0];if(f){const r=new FileReader;r.onload=()=>{el.text.value=String(r.result||"");setStatus("file",f.name);analyze()};r.readAsText(f)}};el.analyze.onclick=analyze;el.pdf.onclick=downloadPdf;el.text.oninput=()=>setStatus(el.text.value.trim()?"draft":"empty");el.sample.onclick=()=>{el.text.value=samples[lang];setStatus("sample");analyze()};el.clear.onclick=()=>{el.text.value="";renderEmpty();el.text.focus()};setLang("en");
